name: aquarriors_game
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  animated_flip_counter: ^0.3.4
  flame: ^1.18.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/Player/
    - assets/images/Scenes/
    - assets/images/Sea Animal/
    - assets/images/Trapped/
    - assets/images/Trash/
    - assets/images/UI/
